---
title: "Flakaliden spruce roots + fungi correlation cluster analysis"
author: "Alonso Serrano"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    number_sections: yes
    toc: yes
---

<style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
  
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(stringr)
conditions <- c("control", "fertilised", "combined")

specie <- "cenococcum_geophilum"
#specie <- "cortinarius_glaucopus"
#specie <- "hyaloscypha_bicolor"
#specie <- "hyaloscypha_variabilis"
#specie <- "piloderma_croceum"

speciesName <- gsub("_"," ",str_to_title(specie))
```

# Introduction
This file contains the script and results of the data from spruce roots and fungi species `r speciesName`
from the 2011 Flakaliden dataset. 


