---
title: "Guild PCA"
author: "Alonso Serrano"
date: "`r Sys.Date()`"
output:
 html_document:
   toc: true
   number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library("DESeq2")
# library(vegan)
# library(ape)
library(dplyr)
library(ggfortify)
```

```{r}
projectFolder <- "/mnt/picea/projects/spruce/vhurry/fungi-flakaliden-2011"
deFolder <- file.path(projectFolder,"DE")
dataFolder <- file.path(projectFolder,"data")
guildFile <- file.path(dataFolder, "fungi.guilds.tsv")
rawFile <- file.path(dataFolder, "kingdom.Fungi.2011.raw.tsv")
metaFile <- file.path(dataFolder, "meta.tsv")
taxonomyFile <- file.path(dataFolder, "gene_taxonomy.tsv")
```

# Read guild file
```{r}
data <- read.table(rawFile, header = T, sep='\t', comment.char = "", quote="", row.names = 1, stringsAsFactors = F)
colnames(data)<-gsub("X", "", colnames(data))

meta <- read.table(metaFile, header = TRUE, sep = '\t', comment.char = "", stringsAsFactors = F)

meta$Treatment <- ifelse(meta$Condition == 'control', 'C', 'F')
meta$Week <- meta$Sampling.date..week..
meta$Time <- substr(meta$Sampling.date..week.., 2,3)
meta$group <- paste0(meta$Week, gsub("T","F",meta$Plot))
meta <- meta[order(meta$group), ]
meta$group <- substr(meta$group, 1, 4)
meta$group <- as.factor(meta$group)
meta$Treatment <- as.factor(meta$Treatment)

#' #remove non usefull samples
data <- data[,colnames(data) %in% meta$Sample.ID]

#' #Order them by group
data <- data[, match(meta$Sample.ID, colnames(data))]

#' change the names of the samples to group
colnames(data) <- paste0(meta$Sampling.date..week..,meta$Plot)

#control data
controlData <- data[,grepl('C',(colnames(data)))]

# fertilised data
fertilisedData <- data[,grepl('F',(colnames(data)))]


#data <- data[(rowSums(data) > 0),]
guilds <- read.table(guildFile, header = TRUE, sep = '\t', comment.char = "", stringsAsFactors = F)
taxo <- read.table(taxonomyFile, header = TRUE, sep = '\t', comment.char = "", stringsAsFactors = FALSE)



```

Trophic modes are: 
Symbiotroph, Saprotroph, Pathotroph-Saprotroph, Pathotroph-Saprotroph-Symbiotroph, Pathotroph, Saprotroph-Symbiotroph, Pathotroph-Symbiotroph, Saprotroph-Pathotroph-Symbiotroph

```{r}
trophicModes <- c("Symbiotroph", "Saprotroph", "Pathotroph-Saprotroph",
                  "Pathotroph-Saprotroph-Symbiotroph", "Pathotroph",
                  "Saprotroph-Symbiotroph", "Pathotroph-Symbiotroph",
                  "Saprotroph-Pathotroph-Symbiotroph")
```


```{r generalPCA, eval=FALSE}

ddsMatrix <- DESeqDataSetFromMatrix(data, colData=meta, design = ~group)
vsd.QA <- varianceStabilizingTransformation(ddsMatrix, blind=TRUE)

assay(vsd.QA) <- assay(vsd.QA) - min(assay(vsd.QA))
vsd.QA.t <- (assay(vsd.QA))
pca <- prcomp(vsd.QA.t)

#match pca with taxo
pca.df <- data.frame(gene = rownames(pca$x), pca$x ,stringsAsFactors = F)
PCAvalues <- left_join(pca.df, taxo, by="gene")
PCAvalues <- left_join(PCAvalues, guilds, by="gene")
# Extract loadings of the variables
PCAloadings <- data.frame(Variables = rownames(pca$rotation), pca$rotation)
percentage <- round(pca$sdev^2 / sum(pca$sdev^2) * 100, 2)
percentage <- paste( colnames(pca$x), "(", paste( as.character(percentage), "%", ")", sep="") )


```

```{r calculateLoadingAvg}
scale=1
var.scale = scale
nobs.factor <- sqrt(nrow(pca$x) - 1)
v <- pca$rotation
d <- pca$sdev
u <- sweep(pca$x, 2, 1 / (d * nobs.factor), FUN = '*')
v <- sweep(v, 2, d^var.scale, FUN='*')
df.v <- v[,1:2]
obs.scale = 1
df.u <- as.data.frame(sweep(u[,1:2], 2, d[1:2]^obs.scale, FUN='*'))
names(df.u) <- c('xvar', 'yvar')
colnames(df.v) <- c('xvar', 'yvar')
df.u <- df.u * nobs.factor
r <- sqrt(qchisq(0.69, df = 2)) * prod(colMeans(df.u^2))^(1/4)
v.scale <- rowSums(v^2)
df.v <- r * df.v / sqrt(max(v.scale))

controlLoadings <- df.v[grepl('C', rownames(df.v)),]
#controlLoadings <- controlLoadings[ , !(names(controlLoadings) %in% "Variables")]
controlLoadings <- colMeans(controlLoadings)
fertilisedLoadings <- df.v[grepl('F', rownames(df.v)),]
#fertilisedLoadings <- fertilisedLoadings[ , !(names(fertilisedLoadings) %in% "Variables")]
fertilisedLoadings <- colMeans(fertilisedLoadings)
newLoadings <- rbind(controlLoadings, fertilisedLoadings)
rownames(newLoadings) <- c("Control", "Fertilised")
newLoadings <- data.frame(newLoadings)
 
# c19 <- colMeans(df.v[grepl('19', rownames(df.v)),])
# c20 <- colMeans(df.v[grepl('20', rownames(df.v)),])
# c21 <- colMeans(df.v[grepl('21', rownames(df.v)),])
# c22 <- colMeans(df.v[grepl('22', rownames(df.v)),])
# c23 <- colMeans(df.v[grepl('23', rownames(df.v)),])
# c24 <- colMeans(df.v[grepl('24', rownames(df.v)),])
# c25 <- colMeans(df.v[grepl('25', rownames(df.v)),])
# c26 <- colMeans(df.v[grepl('26', rownames(df.v)),])
# c28 <- colMeans(df.v[grepl('28', rownames(df.v)),])
# c31 <- colMeans(df.v[grepl('31', rownames(df.v)),])
# c32 <- colMeans(df.v[grepl('32', rownames(df.v)),])
# c34 <- colMeans(df.v[grepl('34', rownames(df.v)),])
# c35 <- colMeans(df.v[grepl('35', rownames(df.v)),])
# c36 <- colMeans(df.v[grepl('36', rownames(df.v)),])
# c37 <- colMeans(df.v[grepl('37', rownames(df.v)),])
# c38 <- colMeans(df.v[grepl('38', rownames(df.v)),])
# c39 <- colMeans(df.v[grepl('39', rownames(df.v)),])
# c40 <- colMeans(df.v[grepl('40', rownames(df.v)),])
# c41 <- colMeans(df.v[grepl('41', rownames(df.v)),])
# 
# newLoadings <- rbind(c19, c20,c21,c22,c23,c24,c25,c26,c28,c31,c32,c34,
#                      c35,c36,c37,c38,c39,c40,c41)
# rownames(newLoadings) <- c("19", "20","21","22","23","24","25","26","28","31","32","34",
#                      "35","36","37","38","39","40","41")
# newLoadings <- data.frame(newLoadings)


```

```{r generalTaxoPCA, eval=T}
# general PCA

g <- ggplot(PCAvalues, aes(x = PC1, y = PC2)) +
  geom_point(size = 0.01) +
  xlab(percentage[1]) +
  ylab(percentage[2]) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank())

png(paste0("generalFungiPCA",".png"), 
  units="px", width=1920, height=1080, res=300)
g
dev.off()

g2 <-  g +
  geom_segment( data= newLoadings,
                aes(x = 0, y = 0, xend = newLoadings$xvar*5, yend = newLoadings$yvar*5),
                arrow = arrow(length = unit(1/2, "picas")),
                color = "red", size = 1) +
        annotate("text", x = (newLoadings$xvar*5), y = (newLoadings$yvar*5),
      label = rownames(newLoadings), colour = "red",size = 5) 

png(paste0("generalFungiPCALoadings.png"), 
  units="px", width=1920, height=1080, res=300)
g2
 dev.off()
```


```{r}
familyColors <- rep("#000000", length(unique(PCAvalues$family)))
names(familyColors) <- unique(PCAvalues$family)

familyColors["Cortinariaceae"]<- "#A4D171"
familyColors["Gloniaceae"]<-  "#009AA9"
familyColors["Atheliaceae"]<-  "#60B266"
familyColors["Hyaloscyphaceae"]<-  "#9BAEC6"

familyTransparency<- vector(mode = "integer", length(unique(PCAvalues$family)))
names(familyTransparency) <- unique(PCAvalues$family)

```



```{r}
families <- c("Cortinariaceae","Gloniaceae","Atheliaceae","Hyaloscyphaceae")
lapply(families, function(fam){
  print(fam)
  myTransparency <- ifelse(names(familyTransparency)==fam, 1, 0)
  names(myTransparency) <- names(familyTransparency)
  
  g <- ggplot(PCAvalues, aes(x = PC1, y = PC2, colour=family, alpha=family)) +
    geom_point(size = 0.01) +
    xlab(percentage[1]) +
    ylab(percentage[2]) +
    scale_alpha_manual(values = myTransparency) +
    scale_color_manual(values=familyColors) +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "none") +
     labs(title=fam)

  png(paste0("taxo_family_",fam,".png"), units="px", width=1920, height=1080, res=300)
  print(g)
  dev.off()

    
      g2 <- ggplot(PCAvalues, aes(x = PC1, y = PC2, colour=family, alpha=family)) +
        geom_segment( data= newLoadings,
                  aes(x = 0, y = 0, xend = xvar*5, yend = yvar*5),
                  arrow = arrow(length = unit(1/2, "picas")),
                  color = "red", size = 1) +
    geom_point(size = 0.01) +
    xlab(percentage[1]) +
    ylab(percentage[2]) +
    scale_alpha_manual(values = myTransparency) +
    scale_color_manual(values=familyColors) +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "none") +
     labs(title=fam)

      g2 <- g + geom_segment(aes(x = 0, y = 0, 
                           xend = newLoadings$xvar[1]*5,
                           yend = newLoadings$yvar[1]*5),
                       arrow = arrow(length = unit(1/2, "picas")),
                       color = "red", size = 1) +
  geom_segment(aes(x = 0, y = 0, 
                   xend = newLoadings$xvar[2]*5,
                   yend = newLoadings$yvar[2]*5),
               arrow = arrow(length = unit(1/2, "picas")),
               color = "red", size = 1) +
           annotate("text", x = (newLoadings$xvar*5), y = (newLoadings$yvar*5),
                     label = rownames(newLoadings), colour = "red",size = 5)
  png(paste0("taxo_family_",fam,"_loadings", ".png"), units="px", width=1920, height=1080, res=300)
  print(g2)
  dev.off()

  # png(paste0("fertilised-",cosa,".png"), 
  #  units="px", width=1920, height=1080, res=300)
  # print(g)
  #  dev.off()
  
})
```


```{r}
trophic.modes <- c("Pathotroph","Pathotroph-Saprotroph",
           "Pathotroph-Saprotroph-Symbiotroph","Pathotroph-Symbiotroph",
           "Saprotroph","Saprotroph-Pathotroph-Symbiotroph",
           "Saprotroph-Symbiotroph","Symbiotroph", "-")
trophicColors=c("#DB3832", "#E26D38",
             "#3F2313", "#764693",
             "#FEDD4F", "#00FF00",
             "#459E55","#264294", "#FFFFFF")

names(trophicColors) <- trophic.modes

trophicTransparency<- vector(mode = "integer", length(unique(PCAvalues$Trophic.Mode)))
names(trophicTransparency) <- trophic.modes

```

```{r}

lapply(trophic.modes, function(fam){
  print(fam)
  myTransparency <- ifelse(names(trophicTransparency)==fam, 1, 0)
  names(myTransparency) <- names(trophicTransparency)
  
  g <- ggplot(PCAvalues, aes(x = PC1, y = PC2, colour=Trophic.Mode, alpha=Trophic.Mode)) +
    geom_point(size = 0.01) +
    xlab(percentage[1]) +
    ylab(percentage[2]) +
    scale_alpha_manual(values = myTransparency) +
    scale_color_manual(values=trophicColors) +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "none") +
     labs(title=fam)

  png(paste0("trophicMode_",fam,".png"), units="px", width=1920, height=1080, res=300)
  print(g)
  dev.off()

    
      g2 <- ggplot(PCAvalues, aes(x = PC1, y = PC2, colour=family, alpha=family)) +
        geom_segment( data= newLoadings,
                  aes(x = 0, y = 0, xend = xvar*5, yend = yvar*5),
                  arrow = arrow(length = unit(1/2, "picas")),
                  color = "red", size = 1) +
    geom_point(size = 0.01) +
    xlab(percentage[1]) +
    ylab(percentage[2]) +
    scale_alpha_manual(values = myTransparency) +
    scale_color_manual(values=familyColors) +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "none") +
     labs(title=fam)

      g2 <- g + geom_segment(aes(x = 0, y = 0, 
                           xend = newLoadings$xvar[1]*5,
                           yend = newLoadings$yvar[1]*5),
                       arrow = arrow(length = unit(1/2, "picas")),
                       color = "red", size = 1) +
  geom_segment(aes(x = 0, y = 0, 
                   xend = newLoadings$xvar[2]*5,
                   yend = newLoadings$yvar[2]*5),
               arrow = arrow(length = unit(1/2, "picas")),
               color = "red", size = 1) +
           annotate("text", x = (newLoadings$xvar*5), y = (newLoadings$yvar*5),
                     label = rownames(newLoadings), colour = "red",size = 5)
  png(paste0("trophicMode_",fam,"_loadings", ".png"), units="px", width=1920, height=1080, res=300)
  print(g2)
  dev.off()

  # png(paste0("fertilised-",cosa,".png"), 
  #  units="px", width=1920, height=1080, res=300)
  # print(g)
  #  dev.off()
  
})
```





































```{r generalPCA, eval=FALSE}

ddsMatrix <- DESeqDataSetFromMatrix(guildData, colData=meta, design = ~group)
vsd.QA <- varianceStabilizingTransformation(ddsMatrix, blind=TRUE)

assay(vsd.QA) <- assay(vsd.QA) - min(assay(vsd.QA))
vsd.QA.t <- (assay(vsd.QA))
pca <- prcomp(vsd.QA.t)
localguilds <- guilds[rownames(guilds) %in% rownames(vsd.QA),]
PCAvalues <- data.frame(Mode = localguilds$Trophic.Mode, pca$x)

# Extract loadings of the variables
PCAloadings <- data.frame(Variables = rownames(pca$rotation), pca$rotation)
percentage <- round(pca$sdev^2 / sum(pca$sdev^2) * 100, 2)
percentage <- paste( colnames(pca$x), "(", paste( as.character(percentage), "%", ")", sep="") )

ggplot(PCAvalues, aes(x = PC1, y = PC2, colour=Mode)) +
  geom_point(size = 1) +
  xlab(percentage[1]) +
  ylab(percentage[2]) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank())
```


```{r generatePCA}
# access by Trophic.Mode or Guild
#removed 150832 genes, because the don't belong to a mode
guildGenes <- rownames(guilds)[guilds$Trophic.Mode != "-"]
# summary of gene distribution by trophic mode
table(guilds[guilds$Trophic.Mode != "-",]$Trophic.Mode)
# guildProbableGenes <- rownames(guilds)[guilds$Trophic.Mode == c("Highly Probable", "Probable")]
#  fix for 3 missmatches
#  
#  activate for control
# data <- controlData
# meta <- meta[meta$Treatment=='C',]

# activate for fertilised
# data <- fertilisedData
# meta <- meta[meta$Treatment=='F',]

guildGenes <- intersect(guildGenes, rownames(data))
guildData <- (data[guildGenes,])

#guild table distribution
guildTable <- table(guilds[guilds$Guild != "-",]$Guild)
#write.table(guildTable, file="guildTable.tsv", sep="\t", quote = F, col.names = F, row.names =F)

ddsMatrix <- DESeqDataSetFromMatrix(guildData, colData=meta, design = ~group)
vsd.QA <- varianceStabilizingTransformation(ddsMatrix, blind=TRUE)

assay(vsd.QA) <- assay(vsd.QA) - min(assay(vsd.QA))
```

```{r test, eval= FALSE}
# dist <- vegdist(assay(vsd.QA),  method = "bray")
# 
# # PCoA is not included in vegan. 
# # We will use the ape package instead
# library(ape)
# PCOA <- pcoa(dist)
# 
# # plot the eigenvalues and interpret
# barplot(PCOA$values$Relative_eig[1:10])
# # Can you also calculate the cumulative explained variance of the first 3 axes?
# 
# # Some distance measures may result in negative eigenvalues. In that case, add a correction:
# PCOA <- pcoa(dist, correction = "cailliez")
# 
# # Plot your results
# biplot.pcoa(PCOA)
# 
# # You see what`s missing? 
# # Indeed, there are no species plotted on this biplot. 
# # That's because we used a dissimilarity matrix (sites x sites) 
# # as input for the PCOA function. 
# # Hence, no species scores could be calculated. 
# #However, we could work around this problem like this:
# biplot.pcoa(PCOA, assay(vsd.QA), rn=rep(".", length(rownames(assay(vsd.QA)))))
```

Pathotrope: #DB3832
Symbiotroph: #264294
Saprotroph: #FEDD4F
Path/Sap: #E26D38
Sap/Sym: #459E55
Path/Sym: #764693
Path/Sap/Sym: #3F2313
```{r plotGroupPCA}
# geneNumber <- length(rownames(assay(vsd.QA)))
# plotPCA(vsd.QA, intgroup = c("Treatment"), ntop=geneNumber)
# plotPCA(vsd.QA, intgroup = c("Week"), ntop=geneNumber)
```
```{r}

vsd.QA.t <- (assay(vsd.QA))
pca <- prcomp(vsd.QA.t)
localguilds <- guilds[rownames(guilds) %in% rownames(vsd.QA),]
probableVector <- localguilds$Confidence.Ranking %in% 
                           c("Highly Probable","Probable")
PCAvalues <- data.frame(Mode = localguilds$Trophic.Mode, 
                        Confidence = localguilds$Confidence.Ranking, pca$x)

# Extract loadings of the variables
PCAloadings <- data.frame(Variables = rownames(pca$rotation), pca$rotation)
percentage <- round(pca$sdev^2 / sum(pca$sdev^2) * 100, 2)
percentage <- paste( colnames(pca$x), "(", paste( as.character(percentage), "%", ")", sep="") )

# controlLoadings <- PCAloadings[grepl('C', rownames(PCAloadings)),]
# controlLoadings <- controlLoadings[ , !(names(controlLoadings) %in% "Variables")]
# controlLoadings <- colMeans(controlLoadings)
# fertilisedLoadings <- PCAloadings[grepl('F', rownames(PCAloadings)),]
# fertilisedLoadings <- fertilisedLoadings[ , !(names(fertilisedLoadings) %in% "Variables")]
# fertilisedLoadings <- colMeans(fertilisedLoadings)
# newLoadings <- rbind(controlLoadings, fertilisedLoadings)
# rownames(newLoadings) <- c("C", "F")
# newLoadings <- data.frame(newLoadings)
#biplot(pca, cex=rep(".", length(rownames(vsd.QA.t))))
#ggplot2::autoplot(pca, label = FALSE, loadings.label = TRUE)

#autoplot(pca, data=localguilds, colour='Guild', loadings.label = F)
```

```{r}

# modes <- c("Pathotroph","Symbiotroph","Saprotroph","Pathotroph-Saprotroph","Saprotroph-Symbiotroph","Pathotroph-Symbiotroph","Pathotroph-Saprotroph-Symbiotroph", "Saprotroph-Pathotroph-Symbiotroph")

modes <- c("Pathotroph","Pathotroph-Saprotroph",
           "Pathotroph-Saprotroph-Symbiotroph","Pathotroph-Symbiotroph",
           "Saprotroph","Saprotroph-Pathotroph-Symbiotroph",
           "Saprotroph-Symbiotroph","Symbiotroph")
modeColors=c("#DB3832", "#E26D38",
             "#3F2313", "#764693",
             "#FEDD4F", "#00FF00",
             "#459E55","#264294")

# modeColors=c("#DB3832", "#264294", "#FEDD4F", "#E26D38", "#459E55", "#764693", "#3F2313", "#00FF00")
modeTransparency= c(0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01)

names(modeColors) <- modes
names(modeTransparency) <- modes
```

autoplot(pca,  loadings.label = T)
```{r}
# DATA <- data.frame(iris)
# 
# # Do PCA
# PCA <- prcomp(iris[,1:4])
# 
# # Extract PC axes for plotting
# PCAvalues <- data.frame(Species = iris$Species, PCA$x)
# 
# # Extract loadings of the variables
# PCAloadings <- data.frame(Variables = rownames(PCA$rotation), PCA$rotation)

    # Plot
ggplot(PCAvalues, aes(x = PC1, y = PC2, colour = Mode)) +
  # geom_segment(data = PCAloadings, aes(x = 0, y = 0, xend = (PC1*25),
  #    yend = (PC2*25)), arrow = arrow(length = unit(1/2, "picas")),
  #    color = "black") +
  geom_point(size = 3) 
  # annotate("text", x = (PCAloadings$PC1*25), y = (PCAloadings$PC2*25),
  #    label = PCAloadings$Variables)
```

```{r generalPCA}
  g <- ggplot(PCAvalues, aes(x = PC1, y = PC2, color=Mode)) +

  geom_point(size = 0.01) +
  scale_color_manual(values=modeColors)+
  xlab(percentage[1]) + ylab(percentage[2]) +
      theme(axis.line = element_line(colour = "black"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank(),
            panel.background = element_blank()) 

png(paste0("generalFertilisedPCA.png"), 
  units="px", width=1920, height=1080, res=300)
g 
 dev.off()
```
```{r}
scale=1
var.scale = scale
nobs.factor <- sqrt(nrow(pca$x) - 1)
v <- pca$rotation
d <- pca$sdev
u <- sweep(pca$x, 2, 1 / (d * nobs.factor), FUN = '*')
v <- sweep(v, 2, d^var.scale, FUN='*')
df.v <- v[,1:2]
obs.scale = 1
df.u <- as.data.frame(sweep(u[,1:2], 2, d[1:2]^obs.scale, FUN='*'))
 names(df.u) <- c('xvar', 'yvar')
colnames(df.v) <- c('xvar', 'yvar')
 

 df.u <- df.u * nobs.factor
   r <- sqrt(qchisq(0.69, df = 2)) * prod(colMeans(df.u^2))^(1/4)
  v.scale <- rowSums(v^2)

  df.v <- r * df.v / sqrt(max(v.scale))
g2 <-  g +
geom_segment( data= data.frame(df.v),
                aes(x = 0, y = 0, xend = xvar*5, yend = yvar*5),
                arrow = arrow(length = unit(1/2, "picas")),
                color = "red") 
# controlLoadings <- df.v[grepl('C', rownames(df.v)),]
# #controlLoadings <- controlLoadings[ , !(names(controlLoadings) %in% "Variables")]
# controlLoadings <- colMeans(controlLoadings)
# fertilisedLoadings <- df.v[grepl('F', rownames(df.v)),]
# #fertilisedLoadings <- fertilisedLoadings[ , !(names(fertilisedLoadings) %in% "Variables")]
# fertilisedLoadings <- colMeans(fertilisedLoadings)
# newLoadings <- rbind(controlLoadings, fertilisedLoadings)
# rownames(newLoadings) <- c("Control", "Fertilised")
# newLoadings <- data.frame(newLoadings)
 
c19 <- colMeans(df.v[grepl('19', rownames(df.v)),])
c20 <- colMeans(df.v[grepl('20', rownames(df.v)),])
c21 <- colMeans(df.v[grepl('21', rownames(df.v)),])
c22 <- colMeans(df.v[grepl('22', rownames(df.v)),])
c23 <- colMeans(df.v[grepl('23', rownames(df.v)),])
c24 <- colMeans(df.v[grepl('24', rownames(df.v)),])
c25 <- colMeans(df.v[grepl('25', rownames(df.v)),])
c26 <- colMeans(df.v[grepl('26', rownames(df.v)),])
c28 <- colMeans(df.v[grepl('28', rownames(df.v)),])
c31 <- colMeans(df.v[grepl('31', rownames(df.v)),])
c32 <- colMeans(df.v[grepl('32', rownames(df.v)),])
c34 <- colMeans(df.v[grepl('34', rownames(df.v)),])
c35 <- colMeans(df.v[grepl('35', rownames(df.v)),])
c36 <- colMeans(df.v[grepl('36', rownames(df.v)),])
c37 <- colMeans(df.v[grepl('37', rownames(df.v)),])
c38 <- colMeans(df.v[grepl('38', rownames(df.v)),])
c39 <- colMeans(df.v[grepl('39', rownames(df.v)),])
c40 <- colMeans(df.v[grepl('40', rownames(df.v)),])
c41 <- colMeans(df.v[grepl('41', rownames(df.v)),])

newLoadings <- rbind(c19, c20,c21,c22,c23,c24,c25,c26,c28,c31,c32,c34,
                     c35,c36,c37,c38,c39,c40,c41)
rownames(newLoadings) <- c("19", "20","21","22","23","24","25","26","28","31","32","34",
                     "35","36","37","38","39","40","41")
newLoadings <- data.frame(newLoadings)

g2 <-  g +
geom_segment( data= newLoadings,
                aes(x = 0, y = 0, xend = newLoadings$xvar*5, yend = newLoadings$yvar*5),
                arrow = arrow(length = unit(1/2, "picas")),
                color = "red", size = 1) +
        annotate("text", x = (newLoadings$xvar*5), y = (newLoadings$yvar*5),
      label = rownames(newLoadings), colour = "red",size = 5) 

png(paste0("averagedFertilisedLoadings.png"), 
  units="px", width=1920, height=1080, res=300)
g2
 dev.off()
```





```{r}
#   g <- ggplot(PCAvalues, aes(x = PC1, y = PC2, color=Mode)) +
#   
#   geom_point(size = 0.01) +
#   scale_color_manual(values=modeColors)+
#   #scale_alpha_manual(values = myTransparency) +
# 
#  
#   xlab(percentage[1]) + ylab(percentage[2]) +
#       theme(axis.line = element_line(colour = "black"),
#             panel.grid.major = element_blank(),
#             panel.grid.minor = element_blank(),
#             panel.border = element_blank(),
#             panel.background = element_blank()) #+
#     # labs(title=cosa)
#   
#    # geom_segment( 
#    #              aes(x = 0, y = 0, xend = newLoadings$PC1[1]*5, yend = newLoadings$PC2[1]*5), 
#    #              arrow = arrow(length = unit(1/2, "picas")),
#    #              color = "black") +
#    #     annotate("text", x = (newLoadings$PC1*5), y = (newLoadings$PC2*5),
#    #    label = rownames(newLoadings)) +
#    #    
# png(paste0("generalPCA.png"), 
#  units="px", width=1920, height=1080, res=300)
# print(g)
#  dev.off()
```

```{r}
lapply(levels(PCAvalues$Mode), function(cosa){
  print(cosa)
  myTransparency <- ifelse(names(modeTransparency)==cosa, 1, 0)
  names(myTransparency) <- modes
  print(myTransparency)
  
  
  g <- ggplot(PCAvalues, aes(x = PC1, y = PC2, color=Mode, alpha=Mode)) +
  
  geom_point(size = 0.01) +
  scale_color_manual(values=modeColors)+
  scale_alpha_manual(values = myTransparency) +

 
  xlab(percentage[1]) + ylab(percentage[2]) +
      theme(axis.line = element_line(colour = "black"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.border = element_blank(),
            panel.background = element_blank()) #+
    # labs(title=cosa)
  
   # geom_segment( 
   #              aes(x = 0, y = 0, xend = newLoadings$PC1[1]*5, yend = newLoadings$PC2[1]*5), 
   #              arrow = arrow(length = unit(1/2, "picas")),
   #              color = "black") +
   #     annotate("text", x = (newLoadings$PC1*5), y = (newLoadings$PC2*5),
   #    label = rownames(newLoadings)) +
   #    
png(paste0("fertilised-",cosa,".png"), 
 units="px", width=1920, height=1080, res=300)
print(g)
 dev.off()
})

```










```{r}

table(guilds[guilds$Trophic.Mode == "Saprotroph",]$Guild)


pcoa <- princomp(vsd.QA.t)
autoplot(pcoa, data=localguilds, colour='Trophic.Mode')

library(cluster)
ggfortify::autoplot.ts(pca, data=localguilds, colour='Trophic.Mode', frame=F,size = 1)

```


