---
title: "meta community DE"
author: "Alonso Serrano"
date: "`r Sys.Date()`"
output:
 html_document:
   toc: true
   number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library("DESeq2")
library(dplyr)
library(plotly)
source('~/Git/UPSCb-common/src/R/gopher.R')
source("~/Git/Rtoolbox/src/plotEnrichedTreemap.R")
source("~/Git/Rtoolbox/src/plotUpAndDown.R")
source("~/Git/Rtoolbox/src/utilsDE.r")
```

```{r}
projectFolder <- "/mnt/picea/projects/spruce/vhurry/fungi-flakaliden-2011"
deFolder <- file.path(projectFolder,"DE")
dataFolder <- file.path(projectFolder,"data")
guildFile <- file.path(dataFolder, "fungi.guilds.tsv")
rawFile <- file.path(dataFolder, "kingdom.Fungi.2011.raw.tsv")
metaFile <- file.path(dataFolder, "meta.tsv")
taxonomyFile <- file.path(dataFolder, "gene_taxonomy.tsv")
```

# Read guild file
```{r}
data <- read.table(rawFile, header = T, sep='\t', comment.char = "", quote="", row.names = 1, stringsAsFactors = F)
colnames(data)<-gsub("X", "", colnames(data))

meta <- read.table(metaFile, header = TRUE, sep = '\t', comment.char = "", stringsAsFactors = F)

meta$Treatment <- ifelse(meta$Condition == 'control', 'C', 'F')
meta$Week <- meta$Sampling.date..week..
meta$Time <- substr(meta$Sampling.date..week.., 2,3)
meta$group <- paste0(meta$Week, gsub("T","F",meta$Plot))
meta <- meta[order(meta$group), ]
meta$group <- substr(meta$group, 1, 4)
meta$group <- as.factor(meta$group)
meta$Treatment <- as.factor(meta$Treatment)

#' #remove non usefull samples
data <- data[,colnames(data) %in% meta$Sample.ID]

#' #Order them by group
data <- data[, match(meta$Sample.ID, colnames(data))]

#' change the names of the samples to group
colnames(data) <- paste0(meta$Sampling.date..week..,meta$Plot)

#control data
controlData <- data[,grepl('C',(colnames(data)))]

# fertilised data
fertilisedData <- data[,grepl('F',(colnames(data)))]

```


```{r}
ddsGroupMatrix <- DESeqDataSetFromMatrix(data, colData=meta, design = ~group)
vsd.Group.QA <- varianceStabilizingTransformation(ddsGroupMatrix, blind=TRUE)

assay(vsd.Group.QA) <- assay(vsd.Group.QA) - min(assay(vsd.Group.QA))

vsd.Group.matrix <- assay(vsd.Group.QA)

ddsGroup <- DESeq(ddsMatrix)

controlVector <- as.character(unique(meta$group[grep("C", meta$group)]))
fertilisedVector <- as.character(unique(meta$group[grep("F", meta$group)]))

combined.res <- mapply(getRes, fertilisedVector, controlVector, 
MoreArgs = list(localDDS=ddsGroup, group="group"))

names(combined.res) <- c("19Fvs19C", "20Fvs20C", "21Fvs21C", "22Fvs22C",
                      "23Fvs23C", "24Fvs24C", "25Fvs25C", "26Fvs26C",
                      "28Fvs28C", "31Fvs31C", "32Fvs32C", "34Fvs34C",
                      "35Fvs35C", "36Fvs36C", "37Fvs37C", "38Fvs38C",
                      "39Fvs39C", "40Fvs40C", "41Fvs41C")
combined.res.filter <- lapply(combined.res, filterDE)

plotUpAndDown(combined.res.filter)

save(ddsGroup, combined.res, file=file.path(deFolder,"ddsGroup.RData"))

resFungiGroup <- combined.res

save(resFungiGroup, file=file.path(deFolder,"resFungiGroup.RData"))

```

```{r DESeqTreatment}
ddsMatrix <- DESeqDataSetFromMatrix(data, colData=meta, design = ~Treatment)
vsd.QA <- varianceStabilizingTransformation(ddsMatrix, blind=TRUE)

# assay(vsd.QA) <- assay(vsd.QA) - min(assay(vsd.QA))
# 
# vsd.Treatment.matrix <- assay(vsd.QA)
# save(vsd.Treatment.matrix, file="vsd.Treatment.QA.RData")

ddsFungiTreatment <- DESeq(ddsMatrix)

resFungiTreatment <- results(ddsTreatment,
        name= "Treatment_F_vs_C",
        filter = rowMedians(counts(ddsTreatment)),
        parallel = FALSE)

save(ddsFungiTreatment, resFungiTreatment, file=file.path(deFolder,"ddsTreatment.RData"))

save(resFungiTreatment, file=file.path(deFolder,"resFungiTreatment.RData"))

```


```{r}

```

```{r sessionInfo}
sessionInfo()
```