---
title: "Untitled"
author: "Alonso Serrano"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi Alon! When you get a chance, could you please run a functional enrichment analysis for me? It's within 

Cortinarius, and we would like to look at Modules 

Cluster1:2:1
Cluster1:1:5
Cluster1:2:2
Cluster1:2:5
Cluster1:1:8

combined, vs the total Cortinarius set

Piloderma, 
for modules 2:1:5 and 2:1:3?

```{r}
library(data.table)
library(here)
library(tidyverse)
library(stringr)
library(reshape2)
library(dplyr)
source("~/Git/Rtoolbox/src/plotEigenGene.R")
source("~/Git/Rtoolbox/src/plotEnrichedTreemap.R")
source('~/Git/Rtoolbox/src/R/gopher.R')
```


```{r}
projectDir <- "/mnt/picea/projects/spruce/vhurry/fungi-flakaliden-2011/fungi-species"

load(file.path("/mnt/picea/projects/spruce/vhurry/fungi-flakaliden-2011/data", "megaData.RData"))
species <- c("cenococcum_geophilum","cortinarius_glaucopus","hyaloscypha_variabilis","hyaloscypha_bicolor","piloderma_croceum")
```

```{r}
#cortinarius_glaucopus$control$data <- file.path(projectDir, "cortinarius_glaucopus",  "DE", "controlVsdData.RData")
# cortinarius_glaucopus_combined_data <- file.path(projectDir, "cortinarius_glaucopus",  "DE", "combinedVsdData.RData")

cortinarius_glaucopus_control_infomap <- read.table(file.path(projectDir, "cortinarius_glaucopus/networks/control/results/aggregated/infomapClusters.tsv"), sep='\t', header=T)

genesInCortinarius <- megaData[megaData$species=="Cortinarius glaucopus",]$gene

megaCluster <- cortinarius_glaucopus_control_infomap[cortinarius_glaucopus_control_infomap$cluster %in% c("Cluster1:2:1", "Cluster1:1:5", "Cluster1:2:2", "Cluster1:2:5", "Cluster1:1:8"),]$gene

enrInCortinarius <- gopher(megaCluster, 
              background = genesInCortinarius, 
              task = c("cog","ko","kog","ko_pathway"),
              url="fungi2011", 
              alpha = 0.05)

enrInCortinariusGO <- gopher(megaCluster, 
              background = genesInCortinarius, 
              task = c("go"),
              url="fungi2011_cortinarius_glaucopus", 
              alpha = 0.05)

enrInCortinarius$ko_pathway <-koPathwayDiseaseCleanup(koTranslate((enrInCortinarius$ko_pathway)))

plotEnrichedTreemap(enrInCortinarius, "ko_pathway", title = "ko_pathway for cortinarius clusters")

```

```{r}
#piloderma_croceum$control$data <- file.path(projectDir, "piloderma_croceum",  "DE", "controlVsdData.RData")
# piloderma_croceum_combined_data <- file.path(projectDir, "piloderma_croceum",  "DE", "combinedVsdData.RData")

piloderma_croceum_control_infomap <- read.table(file.path(projectDir, "piloderma_croceum/networks/control/results/aggregated/infomapClusters.tsv"), sep='\t', header=T)

genesInPiloderma <- megaData[megaData$species=="Piloderma croceum",]$gene

megaCluster_piloderma <- piloderma_croceum_control_infomap[piloderma_croceum_control_infomap$cluster %in% c("Cluster2:1:3", "Cluster2:1:5"),]$gene

enrInPiloderma <- gopher(megaCluster_piloderma, 
              background = genesInPiloderma, 
              task = c("cog","ko","kog","ko_pathway"),
              url="fungi2011", 
              alpha = 0.05)

enrInPilodermaGO <- gopher(megaCluster_piloderma, 
              background = genesInPiloderma, 
              task = c("go"),
              url="fungi2011_piloderma_croceum", 
              alpha = 0.05)

source("~/scripts/koPathwayDiseaesCleanup/koProcessing.R")

enrInPiloderma$ko <- koTranslate((enrInPiloderma$ko))
enrInPiloderma$ko_pathway <-koPathwayDiseaseCleanup(koTranslate((enrInPiloderma$ko_pathway)))

plotEnrichedTreemap(enrInPiloderma, "ko", title = "ko for piloderma clusters")
plotEnrichedTreemap(enrInPiloderma, "kog", title = "kog for piloderma clusters")
plotEnrichedTreemap(enrInPiloderma, "ko_pathway", title = "ko_pathway for piloderma clusters")

```




